### ISSUE TITLE
Does this use distillation training?

### ISSUE THREAD

**Issue by panganqi** [dptech-corp/Uni-Fold#1]
As mentioned in Alphafold2's paper, they use a final dataset of 355,993 sequences and use a self-distillation procedure on unlabelled protein sequences.
For this code implementation, do you use self-distillation or just straightforward training?

**Comment by ZiyaoLi** [comment]
We do not provide explicit code implementations for self-distillation. 
However, self-distillation can be achieved by adding the features and predicted structures into the training dataset.
