### ISSUE TITLE
How to generate features.pkl when using mmseqs2

### ISSUE THREAD

**Issue by nnnwyn** [dptech-corp/Uni-Fold#10]
Hi Ziyao, when i used mmseqs2 to generate MSA, i got six files by searching two databases: .a3m,.dbtype,.index. I noticed that making inference need features.pkl, do you know how to change files mentioned above into features.pkl?

**Comment by ZiyaoLi** [comment]
I think the provided code can automatically do this? If not, you may try to call the `parse_a3m()`[https://github.com/dptech-corp/Uni-Fold/blob/c23f566cf02f4ac2bc3731405b5f2335d5ec0c6a/unifold/data/parsers.py#L127] function on your .a3m files. Together with `make_msa_features()`[https://github.com/dptech-corp/Uni-Fold/blob/c23f566cf02f4ac2bc3731405b5f2335d5ec0c6a/unifold/data/pipeline.py#L33], this would generate partial MSA features ('deletion_matrx_int', 'msa' and 'num_alignements'). Then later you can update these features into your feature dict (i.e. features.pkl).

**Comment by ZiyaoLi** [comment]
Moreover, you may merge multiple MSA features by calling [`make_msa_features()`](https://github.com/dptech-corp/Uni-Fold/blob/c23f566cf02f4ac2bc3731405b5f2335d5ec0c6a/unifold/data/pipeline.py#L33) on joint MSA dictionaries. Find an example command [here](https://github.com/dptech-corp/Uni-Fold/blob/c23f566cf02f4ac2bc3731405b5f2335d5ec0c6a/unifold/data/pipeline.py#L194).
