### ISSUE TITLE
Can unifold multimer be trained with batch_size higher than 1?

### ISSUE THREAD

**Issue by dingquanyu** [dptech-corp/Uni-Fold#112]
Hi,

Sorry again but I wonder if unifold and unifold_multimer can be trained with batch_size higher than 1? I saw in the example script ```per-sample-clip-norm``` is not set to 0 and if it's not 0 then ```batch_size``` should be fixed to 1.  When I set per-sample-clip-norm to 0 and increased the batch_size to more than 1, then the collating function reported an error when it stacked 'asym_len'. 'asym_len' was a 1X2 vector in a dimer but it became 1X4 in a tetramer thus torch.stack() gave this error. 

This makes me wonder maybe unifold was designed only to be trained or finetuned with batch_size=1? 

I look forward to your advice. Thanks a lot

**Comment by ZiyaoLi** [comment]
if you want to use bsz > 1 per gpu, you'll have to fix 3 places:

1. the size of asym_len equals to the number of chains in the multimer. pad this to a constant value if you want to stack the batch. 

2. the calculation of multi-chain permutation alignment is based on bsz=1.

3. the per-sample-clip-norm is implemented based on bsz=1.

**Comment by henrywotton** [comment]
@ZiyaoLi  I see thanks a lot for the advice.
