### ISSUE TITLE
pdb_assembly.json does not agree with train_multi_label.json

### ISSUE THREAD

**Issue by henrywotton** [dptech-corp/Uni-Fold#114]
Hi,

There are some entries in pdb_assembly.json that contains chains which are not listed in train_multi_label.json. Thus, the programme reports a key not found error. For example, in pdb_assembly.json, 7l89 has: ```{'symbol': 'C1', 'stoi': ['A3', 'B3', 'C2'], 'chains': ['F', 'D', 'C', 'E', 'B', 'A', 'H', 'L'], 'opers': ['I', 'I', 'I', 'I', 'I', 'I', 'I', 'I']}```
but in train_multi_label.json dictionary, only ```7l8d_B``` and ```7l87_C``` have chains A, B, C, D, E, and F from ```7l89``` in their values. There are no records for 7l89 H or L in the train_multi_label.json

I've added some extra checking codes to dataset.py myself and now the programme works but I suppose it shouldn't be like this? I believe either pdb_assembly.json or train_multi_label is incorrect? 

Cheers

**Comment by henrywotton** [comment]
I see. Then why are H and L in the pub_assembly.json?

**Comment by guolinke** [comment]
@henrywotton the pdb assembly is from the website (https://github.com/dptech-corp/Uni-Fold/blob/main/scripts/get_pdb_assembly.py), therefore, we cannot filter the chains.

**Comment by henrywotton** [comment]
I see. With current pdb_assembly.json, it will search for corresponding labels within train_multi_label.json and give key not found error. I have filtered pdb_assembly.json myself to solve the issue. Would you like me to upload the filtered version of pdb_assembly.json?

**Comment by henrywotton** [comment]
Hi,

Just in case anyone else also has the same issue, I have uploaded the ```pdb_assembly.json``` to owncloud after I filtered it by myself [here](https://oc.embl.de/index.php/s/DuYfbrXxgbT87Nn). It solved the error for me and please let me know if it also works for you.

Cheers

**Comment by ZiyaoLi** [comment]
thx for the contribution, while I think a run-time filtering of pdb_assemblies would be better. this is actually done in unifold multimer dataset.
