### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by Zhang038** [dptech-corp/Uni-Fold#12]
Hi, I get a question about setting the batch_size. I tried to change the batch_size when it calls sample, seems like the batch_size=1 in the default setting. But it reports an error, like 
```
     rng, prot_idx = self.sample(rng,4)
ValueError: too many values to unpack (expected 2)
```
Could you please tell me how can I change the batch_size? Thank you!

**Comment by ZiyaoLi** [comment]
The `batch_size` argument in the configuration is somehow a legacy when we used to support training multiple sequences on one GPU. As we abandon this option, the batch_size argument should always be set as 1. We will remove this argument from configuration files in the coming version.

**Comment by Zhang038** [comment]
Thanks for the clarification.
