### ISSUE TITLE
Is total_step fixed?

### ISSUE THREAD

**Issue by henrywotton** [dptech-corp/Uni-Fold#120]
Hi,

Sorry again but could I double check on the setting of total_step? I saw it is hard-coded in the example script but I believe this number should be the same as the total number of entries in the ```train_sample_weight.json```  if batch_size is set to 1 right? I've changed it accordingly in my own case. I guess the user is also expected to change total_step case by case right ?

Thanks in advance.

**Comment by ZiyaoLi** [comment]
No. The dataset is randomly sampled instead of shuffled, so the total step is independent with dataset size.

**Comment by henrywotton** [comment]
I see. Thanks for your explanation.
