### ISSUE TITLE
convert_unifold_to_alphafold.py ?

### ISSUE THREAD

**Issue by sokrypton** [dptech-corp/Uni-Fold#14]
Is there a convert_unifold_to_alphafold.py script? 😄

**Comment by guolinke** [comment]
This is a good question.  As described in our preprint (Sec 2.2), we make several modifications to the model architecture, and thus, our model cannot convert back to the original Alphafold JAX framework. 
If you want to run uni-fold in the Colab, we are very happy to help!

**Comment by sokrypton** [comment]
Hi guolinke, will it run in uni-fold-jax?

**Comment by guolinke** [comment]
I think it can't be either. Uni-Fold-Jax uses the same model architecture as AlphaFold.

**Comment by sokrypton** [comment]
Thanks for offer to help running Uni-Fold on Colab!

My first attempt at installing Uni-Core failed :(
https://colab.research.google.com/drive/171kK3kCsAyPf3vXi4PcVrN91Af_tQjfk

**Comment by guolinke** [comment]
Hi @sokrypton 
I saw the CUDA version is 11.2
> | NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2 

while pytorch is `torch.__version__  = 1.12.0+cu113`, which is cuda 11.3.
Therefore, as the compilation needs the same CUDA version of the host machine and PyTorch, it failed. 

So you can use an image with CUDA 11.3, or use our precompiled docker image:  
```
docker pull dptechnology/unifold:pytorch1.11.0-cuda11.3-latest
```

As for the model parameters conversion, ping @BaozCWJ for help.

**Comment by guolinke** [comment]
we just add a colab version of Uni-Fold, https://colab.research.google.com/github/dptech-corp/Uni-Fold/blob/main/notebooks/unifold.ipynb

**Comment by rabbit-0001** [comment]
I run the code in Running Uni-Fold( I change some path)as this:
bash run_unifold.sh /home/input_fasta/1.fasta /home/output  /path/to/database/directory  2020-05-01 multimer_ft    /home/Uni-Fold/all_model/multimer.unifold.pt 
model name is : multimer_ft     model parameters file is:multimer.unifold.pt(in section Downloading the pre-trained model parameters)

but I meet this bug:
<img width="1676" alt="截屏2022-08-12 下午7 40 19" src="https://user-images.githubusercontent.com/97496356/184346830-85f46bff-f836-44e4-af24-0ae683693f29.png">
could u help me?

**Comment by BaozCWJ** [comment]
> I run the code in Running Uni-Fold( I change some path)as this: bash run_unifold.sh /home/input_fasta/1.fasta /home/output /path/to/database/directory 2020-05-01 multimer_ft /home/Uni-Fold/all_model/multimer.unifold.pt model name is : multimer_ft model parameters file is:multimer.unifold.pt(in section Downloading the pre-trained model parameters)
> 
> but I meet this bug: <img alt="截屏2022-08-12 下午7 40 19" width="1676" src="https://user-images.githubusercontent.com/97496356/184346830-85f46bff-f836-44e4-af24-0ae683693f29.png"> could u help me?

It looks weird.  Maybe the parameters doesn't download completely.  Could you please  try to  run the following code:
`
import torch
x = torch.load("./multimer.unifold.pt")['ema']["params"]
 for k in x.keys():
    if "outer_product_mean.layer_norm_out.weight" in k and '0' in k:
        print(k)
`

**Comment by ZiyaoLi** [comment]
Hi @rabbit-0001 is this issue solved?

**Comment by sokrypton** [comment]
@ZiyaoLi does that mean `convert_unifold_to_alphafold.py` was created somewhere? :D

**Comment by ZiyaoLi** [comment]
> @ZiyaoLi does that mean `convert_unifold_to_alphafold.py` was created somewhere? :D

well this actually means that we do not plan to work on this feature, because of Guolin's comment https://github.com/dptech-corp/Uni-Fold/issues/14#issuecomment-1207314159 , and the fact that training with JAX is not a public demand... I close this issue as @rabbit-0001 seems to lose track of his problem.
