### ISSUE TITLE
Release Preprocessed Data/Trained Model/Eval Set

### ISSUE THREAD

**Issue by minhtuev** [dptech-corp/Uni-Fold#14]
Quick question, do you release the preprocessed data/trained model/eval set? We are trying to run UniFold/OpenFold but each protein is taking us around 3 minutes and we want to process as many of them as possible.

**Comment by ZiyaoLi** [comment]
Sorry, we have not released the preprocessed data for Uni-Fold. As a single feature may take up to GB level space, it is hard to release a dataset with considerable number of sequences. BTW to my own experience, 3min/seq is already a high preprocessing speed...

**Comment by minhtuev** [comment]
I see - what do you use for your infrastructure?

**Comment by ZiyaoLi** [comment]
Not sure what you precisely mean by infrastructure. We used 128*A100 to train the net and ~1000 core CPUs to do the preprocessing.
