### ISSUE TITLE
Issues in installation

### ISSUE THREAD

**Issue by Xinheng-He** [dptech-corp/Uni-Fold#15]
During the installation of the current UniFold, I met the problem of conflict packages.

The conflict is caused by:
    The user requested numpy==1.21.0
    biopython 1.79 depends on numpy
    chex 0.0.7 depends on numpy>=1.18.0
    dm-haiku 0.0.4 depends on numpy>=1.18.0
    jax 0.2.14 depends on numpy>=1.12
    jmp 0.0.2 depends on numpy>=1.19.5
    mpi4jax 0.3.2 depends on numpy
    scipy 1.7.0 depends on numpy<1.23.0 and >=1.16.5
    tensorflow 2.5.3 depends on numpy~=1.19.2

When changing the numpy to 1.19.5 in requirements.txt, the bug is fixed. Wish the version of numpy will be changed in the next version of Uni-fold to make it ok to install. Thanks.

**Comment by ZiyaoLi** [comment]
Thank you sincerely for reporting this issue! 
I just revert the previous PR of `bumping numpy 1.19.5 to 1.21.0`. Will check out how to config a proper requirements to satisfy all packages.
