### ISSUE TITLE
train.py: RuntimeError: Resource exhausted: Out of memory while trying to allocate 1090519040 bytes.

### ISSUE THREAD

**Issue by wewewexiao2008** [dptech-corp/Uni-Fold#17]

**Comment by ZiyaoLi** [comment]
Thank you for your interest in Uni-Fold. In your case, I think you can lower the "crop_size" (i.e. the seq len after cropping) in the config file (by default it's 256), and the number of msas (by default 128). Still, 6GB may be too small for training Uni-Fold (notably the default config with fp16 requires at least 32GB).

**Comment by wewewexiao2008** [comment]
Thank you for your in-time response!
