### ISSUE TITLE
Questions about running commands

### ISSUE THREAD

**Issue by Maikuraky** [dptech-corp/Uni-Fold#2]
Hi，Ziyao
I found that there is a problem with the running command in section 4.1 and section 4.2. 
I don't know wether the problem I found is correct or wrong.
In addition, I would like to ask, which graphics card is needed for training, can A100 + CUDA11.4 be trained, thank you.
Here I would like to thank dptech for its contributions to this field.

**Comment by ZiyaoLi** [comment]
Can you please provide the console logs, the command, and potentially the output of the code so that we can locate the problem? thanks.

**Comment by ZiyaoLi** [comment]
A100 + CUDA11.4 is promising for training. We tested for V100 and A100. The CUDA version seems to have little impact. However,  we would also like to remind that the whole process needed to reproduce the training is time-costly (~10d  times 128 A100 cards).
