### ISSUE TITLE
Bug in jupyter notebook cell "Process features for Uni-fold prediction"

### ISSUE THREAD

**Issue by delalamo** [dptech-corp/Uni-Fold#20]
The unifold.ipynb jupyter notebook hits an error when it reaches this function:

```
(
  unpaired_msa,
  paired_msa,
  template_results,
) = get_msa_and_templates(
  target_id,
  unique_sequences,
  result_dir=result_dir,
  msa_mode=msa_mode,
  use_templates=use_templates,
  pair_mode = "unpaired+paired",
  homooligomers_num = homooligomers_num
)
```

Just a heads up that I was able to fix it by removing the line `pair_mode = "unpaired+paired",`.

**Comment by BaozCWJ** [comment]
Thanks for your issue, we have already fix the error at the  pr [#21](https://github.com/dptech-corp/Uni-Fold/pull/21)
