### ISSUE TITLE
loading state_dict

### ISSUE THREAD

**Issue by rabbit-0001** [dptech-corp/Uni-Fold#23]
I run the code in Running Uni-Fold( I change some paths)as this:
bash run_unifold.sh /home/input_fasta/1.fasta /home/output /path/to/database/directory 2020-05-01 multimer_ft /home/Uni-Fold/all_model/multimer.unifold.pt
model name is : multimer_ft 
model parameters file is:multimer.unifold.pt(in section 'Downloading the pre-trained model parameters')

but I meet this bug:
<img width="1662" alt="截屏2022-08-12 下午8 40 16" src="https://user-images.githubusercontent.com/97496356/184355768-d629d39d-2451-41eb-8ed6-e602ad536d17.png">

could u help me?

**Comment by BaozCWJ** [comment]
It looks like the parameters doesn't download completely.
Maybe you can download from google drive via command : `gdown https://drive.google.com/uc?id=1A9iXMYCwP0f_U0FgISJ_6BX7FXZtglvV`

**Comment by guolinke** [comment]
@rabbit-0001 is the issue solved?

**Comment by rabbit-0001** [comment]
Thanks,I have solved this issue

btw, this code covert open-fold model to uni-fold, would u mind giving a link to download open-fold model file

**Comment by guolinke** [comment]
@rabbit-0001 refer to this https://github.com/aqlaboratory/openfold/blob/main/scripts/download_openfold_params.sh

**Comment by addsg** [comment]
hi
I run the command
`bash run_unifold.sh /zhangyudi/alphafold-2.3.1/7XAC.fasta      dummy_test/   /zhangyudi/alphafold_data/   2020-05-01    $model_name    multimer.unifold.pt` 
model name  : multimer_ft
I met this problem
![1](https://github.com/dptech-corp/Uni-Fold/assets/97738331/b48d4dd7-e843-4e82-8dd8-5b284a5a7313)
And I have use the command which had beed mentioned, but it doesn't work
`gdown https://drive.google.com/uc?id=1A9iXMYCwP0f_U0FgISJ_6BX7FXZtglvV`
can u help me?

**Comment by ZiyaoLi** [comment]
@addsg Hi there. It seems that you are using a monomer model while providing a multimer checkpoint.

1. Can you tell me the $model_name variable you are using? By default I think it was model_2 which is a monomer model.
2. Is your target case a monomer or multimer? Please use model name "multimer_ft" for multimer models.

**Comment by addsg** [comment]
model name : multimer_ft
and my target case is a multimer

**Comment by ZiyaoLi** [comment]
sorry I missed the model name you provided. Could you please double check that 1. the code is the newest and 2. the checkpoint is correct and 3. you are using the model name you suggest? 

The reason is that I see in your message the target_feat has shape 22, but if you use multimer_ft as the model name it should be set as 21. See the code https://github.com/dptech-corp/Uni-Fold/blob/b1c89a2cebd4e4ee4c47b4e443f92beeb9138fbb/unifold/config.py#L509 and https://github.com/dptech-corp/Uni-Fold/blob/b1c89a2cebd4e4ee4c47b4e443f92beeb9138fbb/unifold/config.py#L589C9-L589C9.

**Comment by addsg** [comment]
Sorry, I make a mistake. I use a wrong model name. thank u!
