### ISSUE TITLE
The weight of chain_centre_mass loss

### ISSUE THREAD

**Issue by Zhang038** [dptech-corp/Uni-Fold#26]
Hi,
I am a bit confused about the weight you set for chain_centre_mass loss in the final loss, could you please tell me what value you assign to it when training?(I checked the config.py, the default is 0.0)

**Comment by guolinke** [comment]
it is 1.0, refer to this line https://github.com/dptech-corp/Uni-Fold/blob/61202b4002ad2e10fb32d82711a28eca0a41c68e/unifold/config.py#L511

**Comment by Zhang038** [comment]
Thanks a lot!
