### ISSUE TITLE
BladeDISC estimated inference improvement time?

### ISSUE THREAD

**Issue by danpf** [dptech-corp/Uni-Fold#37]
Hello,
Just curious, in your readme you mention that BladeDISC models can be used to speedup inference time, do you have any examples of how much of an improvement it gives? Trying to see if it is worth the trouble of installing it.

thanks!

**Comment by guolinke** [comment]
@yuchaoli can you share some benchmark numbers?

**Comment by yuchaoli** [comment]
Thanks for your interest!
We release our results at https://github.com/alibaba/BladeDISC/tree/main/examples/PyTorch/Inference/CUDA/AlphaFold
