### ISSUE TITLE
Predict from A3M directly ?

### ISSUE THREAD

**Issue by tubiana** [dptech-corp/Uni-Fold#40]
Hi! 

Is it possible to use a MSA directly for the prediction ? 
I already configured colabfold which takes a lot of space in my hard drive and I would like to avoid creating another database (if possible :)) 

THanks!
Best regards,
THibault Tubiana.

**Comment by BaozCWJ** [comment]
I think that some database of ColabFold can be use by Uni-Fold with some annual settings of database path. 
Also, you can try Uni-Fold Colab, which can use the same pipeline as ColabFold for search MSA and template. If you want to run Uni-Fold with ColabFold's MSA file in your local device, maybe you need some effort to rewrite some code from the notebook. Hope it helpful for you.

**Comment by tubiana** [comment]
Hi :) 
Thank you for your reply :) 
I would like to model an oligomer of 12 protein of 500(ish) residues, unfortunatly Google Colab is not enouth powerfull for that..
But I know you are working on a symmetry version of unifold (which is exactly what I need =D), so I might just wait for that :)

**Comment by ZiyaoLi** [comment]
Hi @tubiana we put this (predict directly with a3m) on our todo list and are working on it.

**Comment by FranceCosta** [comment]
Hi @ZiyaoLi. Is there any updates on predicting directly from .a3m?
