### ISSUE TITLE
run_uf_symmetry failed

### ISSUE THREAD

**Issue by Maikuraky** [dptech-corp/Uni-Fold#53]
When running to the inference stage of neural network, it shows:
 ''FileNotFoundError: [Errno 2] No such file or directory: '/Uni-Fold/predicted_structure/10GS/chains.txt'”
Did homo_search.py forget to generate some files?

**Comment by ZiyaoLi** [comment]
Hi @Maikuraky You are right this is a bug. Previous for monomer inputs we do not generate chains.txt, while the symmetry model needs it anyway.

Currently as a hotfix you can manually add a chains.txt file to the folder containing only a letter 'A' (I assume you want 10GS as C2 right?), e.g. by `echo A > chains.txt`.

Working on a fast code fix.

**Comment by ZiyaoLi** [comment]
Plz check if #54 solves this.
