### ISSUE TITLE
convert alphafold checkpoints failed with empty output

### ISSUE THREAD

**Issue by maxshen29** [dptech-corp/Uni-Fold#58]
i get some erro use convert_alphafold_to_unifold.py  ：

incorrect keys: []
missing keys: []

how to check it..

**Comment by ZiyaoLi** [comment]
Hi @maxshen29 can you show us the checkpoint you are converting and the full log of the error so that we can locate the problem? thanks.

**Comment by maxshen29** [comment]
>> Hi @maxshen29 can you show us the checkpoint you are converting and the full log of the error so that we can locate the problem? thanks.
only these logs：
incorrect keys: []
missing keys: []

Where there are full logs？

**Comment by ZiyaoLi** [comment]
This is weird. I would guess that you downloaded bad checkpoints of AlphaFold. Perhaps you can share us your checkpoint.

**Comment by ZiyaoLi** [comment]
It seems that the alphafold parameters are not properly downloaded. For users who are interested in the convertion, the **npz** parameters should be prepared first (by downloading from the alphafold repo).
