### ISSUE TITLE
docker run -d -it --gpus all  --net=host  --name unifold dptechnology/unifold:latest-pytorch1.11.0-cuda11.3 not run 

### ISSUE THREAD

**Issue by maxshen29** [dptech-corp/Uni-Fold#59]

**Comment by maxshen29** [comment]
use  
docker run -d -it --gpus all  --net=host  --name unifold dptechnology/unifold:latest-pytorch1.11.0-cuda11.3
not run 

how to use  dptechnology/unifold:latest-pytorch1.11.0-cuda11.3

**Comment by bernym12** [comment]
I was able to run it. 
You have to pull the image and then you should be able to run it
1. Run `docker pull dptechnology/unifold:latest-pytorch1.11.0-cuda11.3`
2. Run `docker run --gpus all --rm -ti unifold:base bash`

**Comment by maxshen29** [comment]
i  use  , docker run --gpus all --rm -ti dptechnology/unifold:latest-pytorch1.11.0-cuda11.3 bash.
get erro :
exec /usr/bin/bash: no such file or directory

**Comment by guolinke** [comment]
you can use 
```
docker run -d -it --gpus all --net=host --name unifold dptechnology/unifold:latest-pytorch1.11.0-cuda11.3
docker attach unifold
```
to into docker

**Comment by maxshen29** [comment]
> 
get erro
exec /usr/bin/bash: no such file or directory

**Comment by ZiyaoLi** [comment]
> > 
> 
> get erro exec /usr/bin/bash: no such file or directory

did you attached to the docker?

**Comment by bernym12** [comment]
> i use , docker run --gpus all --rm -ti dptechnology/unifold:latest-pytorch1.11.0-cuda11.3 bash. get erro : exec /usr/bin/bash: no such file or directory

Try just `sh` instead of `bash` then

**Comment by ZiyaoLi** [comment]
It appears that the user solved this issue. I'm gonna close this.
