### ISSUE TITLE
Failed to load Uni-Fold checkpoints

### ISSUE THREAD

**Issue by maxshen29** [dptech-corp/Uni-Fold#60]
i  use run_unifold.sh get some erro,how to check it  :
 
start to load params /data/data/unifolddata/params/monomer.unifold.pt
Traceback (most recent call last):
  File "unifold/inference.py", line 266, in <module>
    main(args)
  File "unifold/inference.py", line 91, in main
    model.load_state_dict(state_dict)
  File "/data/miniconda3/envs/unifold/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for AlphaFold:
        Missing key(s) in state_dict: "aux_heads.experimentally_resolved.linear.weight", "aux_heads.experimentally_resolved.linear.bias".

**Comment by ZiyaoLi** [comment]
can you please provide the url you used to download the checkpoints please.

**Comment by ZiyaoLi** [comment]
and don't bother reply in Chinese

**Comment by maxshen29** [comment]
Checkpoints是指？部署过程中感觉没有这个说明呢？


发件人: Ziyao Li ***@***.***>
发送时间: 2022年10月8日 16:51
收件人: dptech-corp/Uni-Fold ***@***.***>
抄送: Max Shen ***@***.***>; Author ***@***.***>
主题: Re: [dptech-corp/Uni-Fold] Failed to load Uni-Fold checkpoints (Issue #60)


and don't bother reply in Chinese

**Comment by ZiyaoLi** [comment]
@maxshen29 指模型参数，需要从Readme里面提供的URL下载解压，见https://github.com/dptech-corp/Uni-Fold#downloading-the-pre-trained-model-parameters

**Comment by maxshen29** [comment]
我就是从这里下载的，我刚发现params 目录下多了一个文件，会不会这个文件有影响，我删除后重新执行下。
谢谢帮助，等会反馈结果。
发件人: Ziyao Li ***@***.***>
发送时间: 2022年10月8日 17:00
收件人: dptech-corp/Uni-Fold ***@***.***>
抄送: Max Shen ***@***.***>; Mention ***@***.***>
主题: Re: [dptech-corp/Uni-Fold] Failed to load Uni-Fold checkpoints (Issue #60)


@maxshen29<https://github.com/maxshen29> 指模型参数，需要从Readme里面提供的URL下载解压，见https://github.com/dptech-corp/Uni-Fold#downloading-the-pre-trained-model-parameters

**Comment by ZiyaoLi** [comment]
比较可能的是你指定的模型名错了。参考


| 任务 task | 参数 parameters | model_name |
| --- | --- | --- |
| 单链预测 monomer prediction | monomer.unifold.pt | model_2_ft |
| 多体预测 multimer prediction | multimer.unifold.pt | multimer_2_ft |

**Comment by maxshen29** [comment]
我检查了下，好像模型名字我写成了 model_2_af2 ：
bash run_unifold.sh     /data/temp/1.fasta  /data/temp/output/20/   /data/data/alldata/   2020-05-01  model_2_af2  /data/data/unifolddata/params/monomer.unifold.pt
fasta 是单体
>T1078 Tsp1, Trichoderma virens, 138 residues|
MAAPTPADKSMMAAVPEWTITNLKRVCNAGNTSCTWTFGVDTHLATATSCTYVVKANANASQASGGPVTCGPYTITSSWSGQFGPNNGFTTFAVTDFSKKLIVWPAYTDVQVQAGKVVSPNQSYAPANLPLEHHHHHH




发件人: Ziyao Li ***@***.***>
发送时间: 2022年10月8日 17:18
收件人: dptech-corp/Uni-Fold ***@***.***>
抄送: Max Shen ***@***.***>; Mention ***@***.***>
主题: Re: [dptech-corp/Uni-Fold] Failed to load Uni-Fold checkpoints (Issue #60)


比较可能的是你指定的模型名错了。参考
任务 task
参数 parameters
model_name
单链预测 monomer prediction
monomer.unifold.pt
model_2_ft
多体预测 multimer prediction
multimer.unifold.pt
multimer_2_ft

**Comment by ZiyaoLi** [comment]
改成model_2_ft解决了吗

**Comment by maxshen29** [comment]
还在执行。 还没执行完成。

发件人: Ziyao Li ***@***.***>
发送时间: 2022年10月8日 17:38
收件人: dptech-corp/Uni-Fold ***@***.***>
抄送: Max Shen ***@***.***>; Mention ***@***.***>
主题: Re: [dptech-corp/Uni-Fold] Failed to load Uni-Fold checkpoints (Issue #60)


改成model_2_ft解决了吗

**Comment by maxshen29** [comment]
改成model_2_ft

看起来正常了，输出了：
drwxr-xr-x. 2 root root  4096 Oct  8 18:17 A
-rw-r--r--. 1 root root 78458 Oct  8 18:05 A.feature.pkl.gz
-rw-r--r--. 1 root root    81 Oct  8 18:17 A.timings.json
-rw-r--r--. 1 root root 15597 Oct  8 18:17 A.uniprot.pkl.gz
-rw-r--r--. 1 root root     1 Oct  8 17:32 chains.txt
-rw-r--r--. 1 root root   170 Oct  8 18:18 model_2_ft_monomer.unifold.pt_42_3_plddt.json
-rw-r--r--. 1 root root 83997 Oct  8 18:18 model_2_ft_monomer.unifold.pt_44732.pdb
-rw-r--r--. 1 root root 83997 Oct  8 18:17 model_2_ft_monomer.unifold.pt_97923.pdb
-rw-r--r--. 1 root root 83997 Oct  8 18:18 model_2_ft_monomer.unifold.pt_99982.pdb


发件人: Ziyao Li ***@***.***>
发送时间: 2022年10月8日 17:38
收件人: dptech-corp/Uni-Fold ***@***.***>
抄送: Max Shen ***@***.***>; Mention ***@***.***>
主题: Re: [dptech-corp/Uni-Fold] Failed to load Uni-Fold checkpoints (Issue #60)


改成model_2_ft解决了吗

**Comment by ZiyaoLi** [comment]
Good to see it works
