### ISSUE TITLE
OOM in multimer

### ISSUE THREAD

**Issue by lhatsk** [dptech-corp/Uni-Fold#66]
Hi,

I'm running into OOM errors in the template module during finetuning (in training and validation) of Uni-Fold-multimer. It happens with multimer_ft and multimer_af2. All targets have at most 3500AA (combined). I'm using a A100 80GB. BF16 is enabled. I'm even more confused that it also happens during training, where the cropping should limit the peak memory consumption. Is there anything I have to keep in mind? I see that you do chunking during inference shouldn't this be also done in eval? Was the 1536AA limit you imposed in the paper tailored to 40GB VRAM? Thanks in advance!

The OOM error occurs here: unifold/modules/template.py", line 229, in forward
    self.tri_att_start(

more specifically in attn = torch.matmul(q, k.transpose(-1, -2)) in attentions.py", line 69

RuntimeError: CUDA out of memory. Tried to allocate 75.09 GiB (GPU 0; 79.17 GiB total capacity; 22.66 GiB already allocated; 51.26 GiB free; 26.60 GiB reserved in total by PyTorch)

**Comment by guolinke** [comment]
Did you use the latest code?

The validation didn't enable crop, and for efficiency purposes, it didn't use chunking.
The training should be safe, if you use the default crop size 384. In our own experiments, the peak GPU memory is about 20GB for multimer_ft/multimer_af2.

**Comment by guolinke** [comment]
you can enable the crop in validation by change these two lines: https://github.com/dptech-corp/Uni-Fold/blob/9123fdb690add058002efa44a4a59601e699b097/unifold/config.py#L200-L201

To further reduce the peak memory cost at training, you can change the following `chunk_size` to 1280 or smaller.

https://github.com/dptech-corp/Uni-Fold/blob/9123fdb690add058002efa44a4a59601e699b097/unifold/modules/attentions.py#L196

**Comment by guolinke** [comment]
BTW, our training data is uploading, and will release in the next few days. You can also try on it.

**Comment by lhatsk** [comment]
Thanks for getting back to me!

Yes, I'm using the latest code with the default crop size. Training works now, not sure what that was about. Validation works if I restrict complexes to a combined 1200AA and if I reduce extra_msa to 512. Tested with bf16 and A100 40GB now. I will try adjust the chunk_size, but isn't the default already at 4 for eval? chunk_size = mlc.FieldReference(4, field_type=int)

**Comment by guolinke** [comment]
The chunk size is not enabled during training, refer to https://github.com/dptech-corp/Uni-Fold/blob/9123fdb690add058002efa44a4a59601e699b097/unifold/config.py#L620-L621.

The training and validation share the same "chunk_size" setting, so enable it will slow down the training.


We actually just use a short monomer for eval, so didn't meet problems. 


It is the processed pickle files, which could be directly used by uni-fold, without further processing.

**Comment by lhatsk** [comment]
> We actually just use a short monomer for eval, so didn't meet problems.

I don't understand this part. You validate multimer_ft with a short monomer? Did you just run multimer_ft (blindly) for 10000 steps and do a proper final validation/ test afterwards?

**Comment by guolinke** [comment]
@lhatsk it means we actually didn't use validation, the one validation data is used to check the correctness of the pipeline (training + validation).  We found the model mostly performs the best in the last checkpoint.

**Comment by lhatsk** [comment]
I see, thanks!
