### ISSUE TITLE
Inferencing using multiple GPUs

### ISSUE THREAD

**Issue by mukulem** [dptech-corp/Uni-Fold#67]
Hi is there any way to use multiple GPU for inferencing, 
I have 4 GPUs, wanna use all of them to inference using multimer model.

Thanks in Advance

**Comment by guolinke** [comment]
If you want data parallel with multiple proteins, you can run 4 different inference pipelines, each with a GPU.

If you want the speedup the inference for single protein by model parallel, you can try BladeDISC, refer to https://github.com/dptech-corp/Uni-Fold#features-introduced-by-the-community

**Comment by mukulem** [comment]
thanks for reply i will definitely check this, 
but i have a single TCR-pMHC with 4 sequences, want to parallelize this for faster inference
