### ISSUE TITLE
Parameter download links wrong

### ISSUE THREAD

**Issue by dominik-handler** [dptech-corp/Uni-Fold#69]
Hi,

I tried to download the database and parameters fresh and ran into problems with the parameters. The download_all script still downloads the alphafold parameters. 
The download instructions in the README are pointing to the wrong files. The normal unifold setup points to the symmetry parameter download and the symmetry instruction points to the normal unifold parameter. 

All the best,
Dominik

**Comment by guolinke** [comment]
Thank you, just fixed that in the latest commit

**Comment by ZiyaoLi** [comment]
Thank you for the suggestions. The bugs are fixed in #70 and #68 separately.
