### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by kdpan** [dptech-corp/Uni-Fold#7]
ERROR: Could not find a version that satisfies the requirement mpi4jax==0.3.2

**Comment by ZiyaoLi** [comment]
Can you please report the conda, pip and C++ version you are using? 

This is likely to be caused by low C++ version that does not satisfy the requirement of mpi4jax==0.3.2.

Would you please Try `pip search mpi4jax==0.3.2` and see if the requirement is met to confirm the above assumption?
