### ISSUE TITLE
Python library to compare actual and predicted structure

### ISSUE THREAD

**Issue by mukulem** [dptech-corp/Uni-Fold#71]
Hi, I was wondering which python library did you use to compare the predicted and actual structure.
<img width="692" alt="image" src="https://user-images.githubusercontent.com/105665325/199346204-4843da4c-808a-4231-aed9-78cd723b25b3.png">
something similar to this.

Thanks

**Comment by lyksj200** [comment]
This is usually compared by a molecular visualization program such as [pymol](https://pymol.org/), [chimera](https://www.rbvi.ucsf.edu/chimera/)(X) or etc.
