### ISSUE TITLE
URL for pre-trained Uni-Fold model parameters not working

### ISSUE THREAD

**Issue by ajbordner** [dptech-corp/Uni-Fold#74]
The URL to download the Uni-Fold model parameters in the README instructions does not work:

wget https://github.com/dptech-corp/Uni-Fold/releases/download/v2.2.0/unifold_params_2022-08-01.tar.gz

**Comment by DimaMolod** [comment]
worked for me when I changed v.2.2.0 to v.2.0.0 in the URL

**Comment by ajbordner** [comment]
Thanks, that link works for me. The link in README.md needs to be updated then.
