### ISSUE TITLE
Problems with Unifold-Symmetry Colab

### ISSUE THREAD

**Issue by jfbazan** [dptech-corp/Uni-Fold#77]
This is something that's popped up in the last few days. I've tried to run the latest version of the Unifold Colab (that also implements UF-Symmetry), and it starts off running well (after I paste in my sequence and set the right symmetry_group), installs the packages, and then crashes with the following error message(s) below. Thanks very much in advance for your consideration of this error. Terrific program (particularly the symmetry option!) and the Colab has been quite useful.

**2022-11-28 17:04:47 (4.55 MB/s) - ‘unicore-0.0.1+cu113torch1.12.1-cp37-cp37m-linux_x86_64.whl’ saved [9428354/9428354]

Cloning into 'Uni-Fold'...
  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1A9iXMYCwP0f_U0FgISJ_6BX7FXZtglvV 

tar (child): unifold_params_2022-08-01.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

 	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses. 

You may still be able to access the file from the browser:

	 https://drive.google.com/uc?id=1UNEGzmueQTxY05QIRweKHxOjr1ht-G_Q 

tar (child): uf_symmetry_params_2022-09-06.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now**

And in the UniFold Prediction on GPU section, another error/fail message:

**start to load params ./uf_symmetry.pt
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
[<ipython-input-4-62cf1f4b0882>](https://localhost:8080/#) in <module>
     21     times=times,
     22     manual_seed=manual_seed,
---> 23     device="cuda:0",                # do not change this on colab.
     24 )

3 frames
[/usr/local/lib/python3.7/dist-packages/torch/serialization.py](https://localhost:8080/#) in __init__(self, name, mode)
    209 class _open_file(_opener):
    210     def __init__(self, name, mode):
--> 211         super(_open_file, self).__init__(open(name, mode))
    212 
    213     def __exit__(self, *args):

FileNotFoundError: [Errno 2] No such file or directory: './uf_symmetry.pt'**

**Comment by ZiyaoLi** [comment]
thx for the report. seems there was an update in either google drive or colab, so that the url is only accessible through webserver. fixed this in #78 by moving the url from google drive to github releases. Along fixed the wheel version in #79 as colab move to python3.
