### ISSUE TITLE
evaluation dataset

### ISSUE THREAD

**Issue by maowayne123** [dptech-corp/Uni-Fold#88]
is it possible to download your evaluation dataset for uni fold? is the evaluation code will be released? thank you

**Comment by ZiyaoLi** [comment]
download the mmcif files using the index in the [evaluation folder](https://github.com/dptech-corp/Uni-Fold/tree/main/evaluation). Eval metrics are implemented in [eval_metrics.py](https://github.com/dptech-corp/Uni-Fold/blob/main/scripts/eval_metrics.py)
