### ISSUE TITLE
How to reproduce the complete Uni-Fold model at full scale?

### ISSUE THREAD

**Issue by HongjianLi** [dptech-corp/Uni-Fold#9]
The training configuration file `unifold/train/train_config.py` allows to specify the features and labels directories for training and evaluation:
```
"data": {
  "train": {
    "features_dir": "where/training/protein/features/are/stored/",
    "mmcif_dir": "where/training/mmcif/files/are/stored/",
    "sample_weights": "which/specifies/proteins/for/training.json"
  },
  "eval": {
    "features_dir": "where/validation/protein/features/are/stored/",
    "mmcif_dir": "where/validation/mmcif/files/are/stored/",
    "sample_weights": "which/specifies/proteins/for/training.json"
  }
}
```
Q1:
For training, what are the complete PDB IDs used to reproduce the exact AlphaFold2 model or the Uni-Fold model at full scale?
The `example_data` directory provides only one PDB ID (i.e. 1ak0) for demonstration purpose: `features/1ak0_1_A/features.pkl` and `mmcif/1ak0.cif`. I'm aware that the complete list of `CIF` files for labels can be obtained from `data_dir/pdb_mmcif/mmcif_files`, which contains 181295 `CIF` files. But how to obtain the same complete list of `fasta` files for generating features (e.g. those `fasta/1ak0_1_A.fasta` files)?

Q2:
For evaluation, what are the PDB IDs that are used for evaluation? I know they are from CASP14 but can you give the exact list in the repository?

Q3:
Is it necessary to remove the PDB IDs for evaluation from training? So that the two datasets do not intersect.

**Comment by ZiyaoLi** [comment]
Q1: 
- We use the same data selection process as that was claimed in the supplemetary materials of AlphaFold2. Specifically, we used all PDB entries before 2020-4-30 to train Uni-Fold.
- We do not provide entries to extract FASTA files from CIF files, yet it can be easily implemented by the function `cif_to_fasta()` at https://github.com/dptech-corp/Uni-Fold/blob/8cc7bcedc23efd53a2f0b11de6657c61ac9204f5/unifold/train/utils.py#:~:text=def-,cif_to_fasta,-(mmcif_object%3A%20MmcifObject%2C .

Q2:
We used all CASP14 entries that was available to us (68 sequences) to evaluate Uni-Fold. The details of Uni-Fold evaluation will be publicated soon.

Q3:
Sure. Using PDB data before 2020-4-30 is specifically proposed for this concern.
