### ISSUE TITLE
想问一下训练资源以及时间

### ISSUE THREAD

**Issue by onlyonewater** [dptech-corp/Uni-Fold#94]
利用这个代码，我手上有8张A100 (80G)，从头开始训练alphafold-multimer大概需要多久呢？

**Comment by ZiyaoLi** [comment]
可以按照https://www.biorxiv.org/content/10.1101/2022.08.04.502811v3.full.pdf table4里128卡时间数线性计算，即乘以16倍。

**Comment by onlyonewater** [comment]
好的，谢谢

**Comment by onlyonewater** [comment]
想问一下，作者，你们这个代码可以在3090上训练嘛？如果有8张3090，每张卡上的batch size是1，在训练的时候会有out of memory现象出现嘛？

**Comment by onlyonewater** [comment]
@ZiyaoLi

**Comment by ZiyaoLi** [comment]
我没有试过。经验上显存占用小于16G。

**Comment by onlyonewater** [comment]
好的，多谢啦！！！
