### ISSUE TITLE
Question about "{}_cluster_size.json"

### ISSUE THREAD

**Issue by shawn-hsyu** [dptech-corp/Uni-Fold#95]
Thank you for sharing this nice repository!

When preparing the data for fine-tuning, I have a question about "{}_cluster_size.json". 
This file is necessary to generate "{}/{}_train_sample_weight.json" file, but I couldn't find any information about "{}_cluster_size.json". 
Could you please explain what it is and how I can create this file?

**Comment by guolinke** [comment]
refer to af2's sample strategy, it will reweight the sequence based on its mmseqs cluster size. 
This JSON file contains the mmseqs cluster size for each sequence. the clustering is performed on the training data.
