### ISSUE TITLE
How did you generate eval_sample_weight.json, train_sample_weight.json etc.

### ISSUE THREAD

**Issue by henrywotton** [dptech-corp/Uni-Fold#97]
Hi,

I wonder how you decided to assign weights to these samples during training and evaluation. BTW could you please upload  all these json files here? I cannot download any of these from modelscope, either via the web interface or download scripts, because of time-out error. I'd really appreciate it if these json files can be uploaded here. 

Thanks

**Comment by ZiyaoLi** [comment]
the train and eval weights are derived from cluster sizes. for small train/eval datasets you may assign 1. for large sets, you may assign 1/cluster_size as alphafold do.
