### ISSUE TITLE
how can I download the training data of multimer only?

### ISSUE THREAD

**Issue by onlyonewater** [dptech-corp/Uni-Fold#98]
I want to train the multimer from scratch, due to my disk memory limitation, I want to download the multimer training data only. Are there any scripts to achieve this goal？

**Comment by ZiyaoLi** [comment]
multimer dataset is almost as large as the monomer dataset (entire pdb), as it is organized as indices of combinations of monomers.

**Comment by onlyonewater** [comment]
so, you means that the multimer dataset is the different combinations of monomers?

**Comment by ZiyaoLi** [comment]
multimers are composed of monomers, so the so called multimer dataset is merely indices on known monomer data.

**Comment by onlyonewater** [comment]
ok, I get it, thanks!
